# -*- coding: utf-8 -*-
"""Desafio_01-DIO_BtCmp_AI102.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QWWDdR2n6K3WU8OSA5beHiminhZiHNQa
"""

pip install requests python-docx

import requests
from docx import Document
import os

subscription_key = "123456789"
endpoint = 'https://api.cognitive.microsofttranslator.com/'
location = "eastus"
language_destination  = 'pt-br'

def translator_text(text, target_language):
    path = '/translate'
    constructed_url = endpoint + path
    headers = {
        'Ocp-Apim-Subscription-Key': subscription_key,
        'Ocp-Apim-Subscription-Region': location,
        'Content-type': 'application/json',
        'X-ClientTraceId': str(os.urandom(16))
    }
    body = [{
        'text': text
    }]
    params = {
        'api-version': '3.0',
        'from': 'fr',
        'to': [target_language]
    }
    request = requests.post(constructed_url, params=params, headers=headers, json=body)
    response = request.json()
    return response[0]["translations"][0]["text"]

translator_text("Au-dessus des vieux volcans Glissent des ailes sous le tapis du vent Voyage, voyage Éternellement", language_destination)

def translate_document(path):
    document = Document(path)
    full_text = []
    for paragraph in document.paragraphs:
        paragraph.text = translator_text(paragraph.text, language_destination)
        full_text.append(paragraph.text)

    translated_document = Document()
    for line in full_text:
        translated_document.add_paragraph(line)
    translated_path = path.replace(".docx", f"_{language_destination}.docx")
    translated_document.save(translated_path)
    return translated_path

input_file = "/content/Letra_Musica Voyage Voyage.docx"
translate_document(input_file)
